### ISSUE TITLE
Tracking issue: VM performance improvements for v0.6

### ISSUE THREAD

**Issue by grjte** [0xPolygonMiden/miden-vm#603]
### Goal(s) 
Improve the performance of the Miden VM.

### Details

We've collected a number of performance-related issues that we'd like to start addressing. For v0.4 in particular, it would be great to address improvements to the range checker, the chiplets bus, and the memory subsystem. It would also be nice to start on some more general trace generation improvements, such as multi-threading and decoder improvements.

```[tasklist]
### Must have
- [ ] https://github.com/0xPolygonMiden/miden-vm/issues/395
- [ ] https://github.com/0xPolygonMiden/miden-vm/issues/394
- [ ] https://github.com/0xPolygonMiden/miden-vm/issues/446
```

```[tasklist]
### Nice to have
- [ ] https://github.com/0xPolygonMiden/miden-vm/issues/299
- [ ] https://github.com/0xPolygonMiden/miden-vm/issues/606
- [ ] trace generation improvements (e.g. decoder, multi-threading, some performance-related TODOs in the code)
```

### Working group:

<details>
<summary>Workflow</summary>

- Discussion should happen here or in the related sub-issues.
- PRs should only be merged by the coordinator, to ensure everyone is able to review.
- Aim to complete reviews within 24 hours.
- When a related sub-issue is opened:
    - add it to the list of sub-issues in this tracking issue
- When opening a related PR:
    - request review from everyone in this working group
- When a sub-issue is completed:
    - close the related issue with a comment that links to the PR where the work was completed
</details>

### Coordinator:  

<details>
<summary>Workflow</summary>

The working group coordinator ensures scope & progress tracking are transparent and accurate. They will:

- Merge approved PRs after all working group members have completed their reviews.
    - add the PR # to the relevant section of the current tracking PR.
    - close any completed sub-issue(s) with a comment that links to the PR where the work was completed
- Monitor workflow items and complete anything that slips through the cracks.
- Monitor scope to see if anything is untracked or unclear. Create missing sub-issues or initiate discussion as required.
- Monitor progress to see if there's anything which isn't moving forward. Initiate discussion as required.
- Identify PRs with especially significant changes and add @grjte and @bobbinth for review.
</details>

**Comment by bobbinth** [comment]
Closing this tracking issue as we'll address individual issues separately.
