### ISSUE TITLE
Tracking issue: STARK verifier added to the standard library

### ISSUE THREAD

**Issue by grjte** [0xPolygonMiden/miden-vm#717]
### Goal(s)
- be able to support recursive verification for Miden VM

### Details

Now that we have a FRI verifier (#548), we need to write a Miden assembly implementation of a full STARK verifier in order to support recursive verification of proofs of execution in the Miden VM.

```[tasklist]

### Must have

- [ ] https://github.com/0xPolygonMiden/miden-vm/issues/751
- [ ] https://github.com/0xPolygonMiden/miden-vm/issues/752
- [ ] https://github.com/0xPolygonMiden/miden-vm/issues/753
- [ ] https://github.com/0xPolygonMiden/miden-vm/issues/754
- [ ] Implement proof-of-work verification
```

```[tasklist]

### Nice to have

```

## Working group:
@Al-Kindi-0, @bobbinth 

<details>
<summary>Workflow</summary>
    
- Discussion should happen here or in the related sub-issues.
- PRs should only be merged by the coordinator, to ensure everyone is able to review.
- Aim to complete reviews within 24 hours.
- When a related sub-issue is opened:
    - add it to the list of sub-issues in this tracking issue
- When opening a related PR:
    - request review from everyone in this working group
- When a sub-issue is completed:
    - close the related issue with a comment that links to the PR where the work was completed
    
</details>

### Coordinator: @Al-Kindi-0
<details>
    
The working group coordinator ensures scope & progress tracking are transparent and accurate. They will:

- Merge approved PRs after all working group members have completed their reviews.
    - add the PR # to the relevant section of the current tracking PR.
    - close any completed sub-issue(s) with a comment that links to the PR where the work was completed
- Monitor workflow items and complete anything that slips through the cracks.
- Monitor scope to see if anything is untracked or unclear. Create missing sub-issues or initiate discussion as required.
- Monitor progress to see if there's anything which isn't moving forward. Initiate discussion as required.
- Identify PRs with especially significant changes and add @grjte and @bobbinth for review.
</details>

**Comment by Al-Kindi-0** [comment]
To serve as a reference for future discussions, here is a simple outline of the parts making up the STARK verifier for Miden VM. This is adapted to the case of blowup factor 8, maximum degree 9 and 1 auxiliary trace segment.
1. Load public input:
   1. Stack input
   2. Stack output
   3. Program hash
   4. Kernel: `Vec<Word>`.
This is done using `advice_pipe` and assuming that the length of the vector of kernels is upper bounded by a fixed number in order to simplify memory management[^1]. `advice_pipe` will result in a digest which is going to be the seed initializing our random oracle for Fiat-Shamir, call it `public_coin`. 

2. Read trace commitments:
We have the main trace and one auxiliary trace and hence two commitments `trace_commitment[0]` and `trace_commitment[1]`. Then:
   1. Reseed `public_coin` with `trace_commitment[0]`.
   2. Draw random elements `aux_rand_elements` used in the auxiliary trace segment using `public_coin`
   3. Reseed `public_coin` with `trace_commitment[1]`.

3. Draw `constraint_coefficients` from `public_coin`
These are tuples $(\alpha_i, \beta_i)$ used in computing the sum $$\sum_{i = 0}^k{C_i(x) \cdot (\alpha_i + \beta_i \cdot x^{d_i})}$$ where $C_i$ is the $i$-th constraint and $d_i$ is its corresponding degree adjustment.

4. Get `constraint_commitment` and reseed `public_coin` with it.

5. Draw the random Out-Of-Domain field element $z$

6. Read `[[ood_main_trace_frame], [ood_aux_trace_frame]]`
7. Reseed with `[[ood_main_trace_frame.current(), ood_aux_trace_frame.current()], [ood_main_trace_frame.next(), ood_aux_trace_frame.next()]]`
8. Evaluate constraints computing `ood_constraint_eval_1` using:
   1. `constraint_coefficients`
   2. `ood_main_trace_frame`
   3. `ood_aux_trace_frame`
   4. `aux_random_elements`
   5. `z`
9. Get `ood_constraint_evaluations` which is just a length `m = 8` array of extension field elements `[value_0, ... , value_{m-1}]` and use it to compute `ood_constraint_eval_2` as $\Sigma_{i =0}^{m-1} z^i value_i$.  
10. Assert `ood_constraint_eval_1 == ood_constraint_eval_2`
11. Reseed with `ood_constraint_evaluations`
12. Draw `deep_composition_coefficients` which are $\alpha_i$, $\beta_i$, $\gamma_i$ and $\delta_i$ used to compute the one-value-per-trace-row $$Y(x) = \sum_{i=0}^k{\left(\alpha_i \cdot \frac{T_i(x) - T_i(z)}{x - z} +\beta_i \cdot \frac{T_i(x) - T_i(z \cdot g)}{x - z \cdot g} +\gamma_i \cdot \frac{T_i(x) - T_i(\overline{z})}{x - \overline{z}}\right)} + \sum_{j=0}^{m-1}{\delta_j \cdot \frac{H_j(x) - H_j(z^m)}{x - z^m}}$$
   To bring the degree bound to be equal to trace length minus 1 we use $\lambda$ and $\mu$ to compute the degree-adjusted quantity
   $$C(x) = Y(x) \cdot (\lambda + \mu \cdot x)$$
13. Get power-of-work nonce `pow_nonce` and reseed `public_coin` with it.
14. Check that the resulting internal seed of `public_coin` contains the correct number of leading zeros.
15. Draw `query_positions` which are row indices ranging from 0 to the length of LDE domain minus 1.
16. Get the queries at the `query_positions` of:
    1.  `queried_main_trace_states`
    2.  `queried_aux_trace_states`
    3.  `queried_constraint_evaluations`
    These are unhashed arrays from leafs that were authenticated against previously received Merkle tree commitments i.e.  `trace_commitment[0]`, `trace_commitment[1]` and `constraint_commitment`.
17. Using `query_positions`, `z` and `deep_composition_coefficients` compute:
    1.  `t_composition := compose(queried_main_trace_states, queried_aux_trace_states, ood_main_trace_frame, ood_aux_trace_frame)`
    2.  `c_composition := compose(queried_constraint_evaluations, ood_constraint_evaluations)`
18. Compute `deep_evaluations = combine(t_composition, c_composition)`
19. Lay out `query_positions` and `deep_evaluations` in memory in preparation for FRI verification.
20. Read FRI layer commitments and use them to seed the `public_coin` and draw the next folding challenge $\alpha$. Lay out in memory the layer commitment followed by `[d_size, t_depth, alpha_1, alpha_0]` for each FRI layer.
21. Read the remainder codeword together with remainder polynomial coefficients and lay them out in memory.
22. Call `FRI_Verifier`

The above assumes that the FRI verification procedure has been updated in two ways:
1. The stack input for FRI verification has been updated from `[layer_ptr ... rem_ptr ... query_start_ptr ... query_end_ptr]` to  `[query_ptr ... layer_ptr ... rem_ptr]`.
2. The STARK verifier lays out the remainder codeword using `adv_pipe` and compares the resulting hash with the commitment received from the prover. It then continues using `adv_pipe` to lay out the remainder polynomial coefficients in order to compute the challenge points $\tau$ for the remainder verification procedure. The STARK verifier determines, based on the `lde_domain_size`, which of `verify_remainder_32` or `verify_remainder_64` to use.




[^1]: Is this a reasonable assumption?

**Comment by Al-Kindi-0** [comment]
Here is a tentative proposal for how the memory should be laid out. Since the number of queries is fixed and by putting an upper bound on the number of FRI layers, we can make all of the memory manipulations static and thus increase the performance of the resulting code.
![STARK_memory_layout](https://user-images.githubusercontent.com/82364884/223149188-2dc649a6-12ae-4d39-b170-0e4e354ddc75.png)

**Comment by hackaugusto** [comment]
Question: Do we have a well of telling which version of AIR the proof corresponds to? I suppose this can be done out-of-band if not, but eventually we will rollout changes to the AIR constraints, and we will end up in a situation with local proofs generated for more than one version of the constraint, when the sequencer needs to verify the local proofs it needs a way to identify the version of AIR used.

**Comment by bobbinth** [comment]
@hackaugusto - no way currently, but that's something we can probably track as a part of [ExecutionProof](https://github.com/0xPolygonMiden/miden-vm/blob/main/air/src/proof.rs#L16) struct.

**Comment by bobbinth** [comment]
@Al-Kindi-0 - this is awesome! Thank you for putting it together.

I agree with the preliminary layout proposal - though, I do think we'll probably change it a few times as we work though the actual implementation.

By the way, looking at this now, I am rather pessimistic that we can complete all non-FRI steps in about 40K cycles. Seems like step 17 alone could be about 40K cycles. I'd probably create a separate sub-task for it as we may try figure out was to optimize it (i.e., maybe we can remove the conjugate constraint check from Winterfell).

**Comment by Al-Kindi-0** [comment]
Thank you @bobbinth !
I add #754 to track point 17.

**Comment by Al-Kindi-0** [comment]
I remember Eli tweeted that the third term is not needed but I can't find the justification written anywhere.
As for needing a new instruction, I think it might make sense if we remove the third term. In this case, there will be 8 extension field elements and thus 16 (top) stack elements.

**Comment by bobbinth** [comment]
The tweet is [here](https://twitter.com/EliBenSasson/status/1625140730736828416) (and it does reference some part of the paper).

I actually count 6 elements in the extension field and 2 elements in the base field ($T_i(x)$ and $x$ are in the base field, right?).

**Comment by Al-Kindi-0** [comment]
Yes, you are correct. The trace elements and LDE domain coordinates are in the base field. So overall 14 base field elements.
