### ISSUE TITLE
Tracking issue: Optimize STARK recursive verifier

### ISSUE THREAD

**Issue by Al-Kindi-0** [0xPolygonMiden/miden-vm#858]
### Goal(s)
- improve support for recursive verification in Miden VM standard library.

### Details

Now that we have a basic STARK verifier (#717), we need to tackle several aspects in order to make it both more general as well as more performant.

```[tasklist]
### Must have
- [ ] https://github.com/0xPolygonMiden/miden-vm/issues/881
- [x] Optimize the computation of the Deep composition polynomial queries #915
```

```[tasklist]
### Must have (Winterfell)
- [x] #877
- [x] Change how DEEP composition polynomial is constructed
- [x] #875
```

```[tasklist]
### Nice to have
- [x] https://github.com/0xPolygonMiden/miden-vm/issues/925
- [x] https://github.com/0xPolygonMiden/miden-vm/issues/926
```

## Working group:
@Al-Kindi-0, @bobbinth 

<details>
<summary>Workflow</summary>
    
- Discussion should happen here or in the related sub-issues.
- PRs should only be merged by the coordinator, to ensure everyone is able to review.
- Aim to complete reviews within 24 hours.
- When a related sub-issue is opened:
    - add it to the list of sub-issues in this tracking issue
- When opening a related PR:
    - request review from everyone in this working group
- When a sub-issue is completed:
    - close the related issue with a comment that links to the PR where the work was completed
    
</details>

### Coordinator: @Al-Kindi-0
<details>
    
The working group coordinator ensures scope & progress tracking are transparent and accurate. They will:

- Merge approved PRs after all working group members have completed their reviews.
    - add the PR # to the relevant section of the current tracking PR.
    - close any completed sub-issue(s) with a comment that links to the PR where the work was completed
- Monitor workflow items and complete anything that slips through the cracks.
- Monitor scope to see if anything is untracked or unclear. Create missing sub-issues or initiate discussion as required.
- Monitor progress to see if there's anything which isn't moving forward. Initiate discussion as required.
- Identify PRs with especially significant changes and add @grjte and @bobbinth for review.
</details>

**Comment by Al-Kindi-0** [comment]
Sure! Here or in Winterfell repo?

**Comment by bobbinth** [comment]
Probably here would be best for now.
