### ISSUE TITLE
Tracking issue: finalize execution trace generation in the VM

### ISSUE THREAD

**Issue by grjte** [0xPolygonMiden/miden-vm#867]
### Goal(s)
Our main goal is to finalize trace generation in the processor so that everything that happens during execution is in the trace.

### Details
In particular, we want to finalize the kernel ROM trace and we want to support new instructions.

```[tasklist]
### Must have
- [x] Trace generation for [kernel ROM](https://github.com/0xPolygonMiden/miden-vm/issues/231#issuecomment-1180007490) lookups
- [ ] https://github.com/0xPolygonMiden/miden-vm/issues/884
```

```[tasklist]
### Nice to have
- [ ] https://github.com/0xPolygonMiden/miden-vm/issues/728
```

**Comment by bobbinth** [comment]
Must haves were completed in #939 and #887.
